iam_role_name: airflow_matrix_scraper

athena:
  write: true

glue_job: true

secrets: false

s3:
  read_only:
    - alpha-dag-occupeye/*
  read_write:
    - alpha-app-matrixbooking/*
    - alpha-dag-matrix/*